[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config", "mysqlclient"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ". .venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn hostel_management.wsgi"
