# Generated by Django 5.0.1 on 2025-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostel_name", models.CharField(max_length=100, unique=True)),
                ("total_rooms", models.IntegerField()),
                ("warden_name", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
