# Generated by Django 5.0.1 on 2025-12-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=50, unique=True)),
                ("contact_no", models.CharField(max_length=15)),
                ("parent_contact", models.CharField(max_length=15)),
                ("stream", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=10)),
                ("year", models.CharField(max_length=20)),
                ("hostel_name", models.CharField(max_length=100)),
                ("room_no", models.CharField(max_length=10)),
                ("taluka", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
